[package]
name = "richclip"
version = "0.1.0"
edition = "2021"
authors = ["beeender"]

[dependencies]
anyhow = "1.0.94"
daemonize = "0.5.0"
env_logger = "0.11.5"
log = "0.4.22"
wayrs-client = "1.1.3"
wayrs-protocols = { version = "0.14.4",  features = ["wlr-data-control-unstable-v1"] }
